Added CMake function to make Doxygen theme available.
Added the setup_doxygen_build() CMake function to automatically download the
doxygen-awesome Doxygen theme during the build configure phase and place it in
a known location under the build tree. The Doxyfile is changed to load the
custom CSS and JS resources.

Signed-off-by: kilo52 <phil.gaiser@raven-computing.com>

diff --git a/share/var/script_build_docs_doxygen_main b/share/var/script_build_docs_doxygen_main
--- a/share/var/script_build_docs_doxygen_main
+++ b/share/var/script_build_docs_doxygen_main
@@ -5,6 +5,10 @@ if [[ $ARG_DOCS == true ]]; then
   ${{VAR_SCRIPT_BUILD_ISOLATED_HINT1}}
     exit 1;
   fi
+  if ! [ -d "build/_deps/doxygen-theme" ]; then
+    echo "Warning: Doxygen theme not found in build tree.";
+    echo "Warning: Execute the build configure step before building the documentation";
+  fi
   echo "Building documentation";
   doxygen "docs/Doxyfile" &> /dev/null;
   docs_status=$?;
