Added check to automatically execute configure step.
Signed-off-by: kilo52 <phil.gaiser@raven-computing.com>

diff --git a/share/var/script_build_docs_doxygen_main b/share/var/script_build_docs_doxygen_main
--- a/share/var/script_build_docs_doxygen_main
+++ b/share/var/script_build_docs_doxygen_main
@@ -7,7 +7,11 @@ if [[ $ARG_DOCS == true ]]; then
   fi
   if ! [ -d "build/_deps/doxygen-theme" ]; then
     echo "Warning: Doxygen theme not found in build tree.";
-    echo "Warning: Execute the build configure step before building the documentation";
+    echo "Warning: Executing build configure step before building the documentation";
+    if ! bash build.sh --config; then
+      echo "Error: Build configure step has failed";
+      exit 1;
+    fi
   fi
   echo "Building documentation";
   doxygen "docs/Doxyfile" &> /dev/null;
