Changed Doxygen theme setup to use CMake script mode with util function.
Changed the DocsUtil.cmake script to be able to run independently in CMake
script mode but still be includable from other CMake code if necessary.
Removed SCRIPT_CMAKE_DOCS_SETUP substitution variable.

Signed-off-by: kilo52 <phil.gaiser@raven-computing.com>

diff --git a/share/var/script_build_docs_doxygen_main b/share/var/script_build_docs_doxygen_main
--- a/share/var/script_build_docs_doxygen_main
+++ b/share/var/script_build_docs_doxygen_main
@@ -5,13 +5,10 @@ if [[ $ARG_DOCS == true ]]; then
   ${{VAR_SCRIPT_BUILD_ISOLATED_HINT1}}
     exit 1;
   fi
-  if ! [ -d "build/_deps/doxygen-theme" ]; then
-    echo "Warning: Doxygen theme not found in build tree.";
-    echo "Warning: Executing build configure step before building the documentation";
-    if ! bash build.sh --config; then
-      echo "Error: Build configure step has failed";
-      exit 1;
-    fi
+  echo "Configuring documentation";
+  if ! cmake -P "cmake/DocsUtil.cmake"; then
+    echo "CMake Error: Documentation configure step has failed";
+    exit 1;
   fi
   echo "Building documentation";
   doxygen "docs/Doxyfile" &> /dev/null;
